### ISSUE TITLE
[Tracking] Use `buildx bake` to build images

### ISSUE THREAD

**Issue by eitsupi** [rocker-org/rocker-versioned2#199]
- [x] Add a script for generate `docker-bake.json` files from the stack files. (#198)
- [x] Minor modifications to the stack files and the existing scripts to support setting multi-platform and multi-tagging.
  - [x] `stacks/binder-.*json` (#215)
  - [x] `stacks/geospatial-.*json` (#212)
  - [x] `stacks/ml-cuda10.1-.*json` (#212)
- [x] Create commands that executes `buildx bake` commands continuously while changing targets. Update the `Makefile`. (#220)
- [x] Switch `docker-compose build` to `docker buildx bake` in GitHub Actions build workflow. (#220, #226)
- [x] More [OCI pre-defined annotations](https://github.com/opencontainers/image-spec/blob/main/annotations.md). (I think it would be useful to be able to show these in the reports.)
  - [x] `org.opencontainers.image.revision` (#220)
  - [x] `org.opencontainers.image.version` (#227)
  - [x] `org.opencontainers.image.title` (#227)
  - [x] `org.opencontainers.image.description` (#227)
  - [x] `org.opencontainers.image.base.name` (#227)
- [x] Multi-architecture (amd64 & arm64) build. (#242)
- [x] Add tests for `docker-bake.json` files. (Test if the bake files generated from the stack files are correct with `bake --print` command) (#239)

**Comment by eitsupi** [comment]
FYI, I mentioned in https://github.com/rocker-org/rocker-versioned2/pull/214#issuecomment-896990256 that it is difficult to merge the currently separated stack files into `X.Y.Z.json` for build convenience, but after we use the `bake` command to build, the GitHub Actions restriction will be removed.

For example, if we want to extract only `r-ver`, `rstudio`, `tidyverse`, and `verse` from `devel.docker-bake.json` for daily build, we only have to prepare a file `build/develdaily.hcl` like the following:

```hcl
group "default" {
    targets = ["r-ver", "rstudio", "tidyverse", "verse"]
}
```

By merging this file with `devel.docker-bake.json`, only the default targets will be extracted.

```shell
$ docker buildx bake --print -f tmp/develbuild.hcl -f bakefiles/devel.docker-bake.json
[+] Building 0.0s (0/0)                                                                                                               
{
   "target": {
      "r-ver": {
         "context": "./",
         "dockerfile": "dockerfiles/Dockerfile_r-ver_devel",
         "tags": [
            "docker.io/rocker/r-ver:devel"
         ],
         "platforms": [
            "linux/amd64"
         ]
      },
      "rstudio": {
         "context": "./",
         "dockerfile": "dockerfiles/Dockerfile_rstudio_devel",
         "tags": [
            "docker.io/rocker/rstudio:devel"
         ],
         "platforms": [
            "linux/amd64"
         ]
      },
      "tidyverse": {
         "context": "./",
         "dockerfile": "dockerfiles/Dockerfile_tidyverse_devel",
         "tags": [
            "docker.io/rocker/tidyverse:devel"
         ],
         "platforms": [
            "linux/amd64"
         ]
      },
      "verse": {
         "context": "./",
         "dockerfile": "dockerfiles/Dockerfile_verse_devel",
         "tags": [
            "docker.io/rocker/verse:devel"
         ],
         "platforms": [
            "linux/amd64"
         ]
      }
   }
}
```

**Comment by eitsupi** [comment]
Now the first `rocker/r-ver` arm64 build was published! https://github.com/rocker-org/rocker-versioned2/wiki/r-ver_a0de2f064e13

```shell
$ docker run --rm -it rocker/r-ver:latest R -q -e 'sessionInfo()'
> sessionInfo()
R version 4.1.1 (2021-08-10)
Platform: aarch64-unknown-linux-gnu (64-bit)
Running under: Ubuntu 20.04.3 LTS

Matrix products: default
BLAS/LAPACK: /usr/lib/aarch64-linux-gnu/openblas-pthread/libopenblasp-r0.3.8.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=C
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
[1] compiler_4.1.1
```

All tasks are done so close this issue.
