### ISSUE TITLE
[Tracking] Build reports on the wiki

### ISSUE THREAD

**Issue by eitsupi** [rocker-org/rocker-versioned2#222]
- [x] First setting. (#211)
- [x] Set the side bar. (#334)
- [x] Better file name (ex. `r-ver_728f0bd6629a.md`) (#238)
- [x] Show the default non-root user's name. (#227)
- [x] Show platforms for multi-arch build. (#246)
- [x] Show ENTRYPOINT and CMD. (#316)
- [x] Show EXPOSE. (#321)
- [x] Add a new page about version specific configurations. (#334)
